services:
  eventosvivos.api:
    image: ${DOCKER_REGISTRY-}eventosvivosapi
    build:
      context: .
      dockerfile: API/EventosVivos.API/Dockerfile

  PostgreSql:
     container_name: PostgreSql

  Redis:
     container_name: Redis
