services:
  eventosvivos.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__PostgreSqlConnection=Host=PostgreSql;Port=5432;Database=EventosVivos;Username=postgres;Password=YourStrong!Passw0rd
      - ConnectionStrings__RedisConnection=Redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - PostgreSql
      - Redis

  PostgreSql:
    image: postgres:17-alpine
    container_name: PostgreSql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "YourStrong!Passw0rd"
      POSTGRES_DB: EventosVivos
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  Redis:
    image: redis:latest
    platform: "linux/amd64"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
    pg_data:
    redis-data: